### ISSUE TITLE
Review log summary

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1186]
For the CLI output for checks status:
- why does a warning include the text `Only`?   `Only 1 warning. 0 failure. 0 error. 0 pass.` If there are more than one warnings, the `Only` is still there: `Only 2 warnings. 0 failure. 0 errors. 0 pass.`  Are `50` warnings still `Only`? `100`?   Maybe we could use a different word, like `Note`. (However,  the failures trump the warnings in order of precedence so 1 failure and 2 warnings seems fine.  `Oops! 1 failure. 2 warnings. 0 errors. 0 pass.`)
- Sometimes it says `0 warnings` and sometimes it says `No warnings`— is that intentional? `All is good. No failures. No warnings. No errors.`   `Oops! 1 failure. 0 warnings. 0 errors. 0 pass.` I suppose I am advocating for consistency when the status is 0/none.
- Can we change the output message to apply plural where appropriate? `Oops! 1 failures.`   `0 pass.`  `2 pass.`  `0 failure`
`Why does the word  `Oops!` appear when there is a failure? It implies that something is wrong when, really, a failed test means that something is working correctly/as expected!  Maybe instead: `Note` ?

**Comment by tombaeyens** [comment]
Also @janet-can gave input on this earlier: https://sodadata.slack.com/archives/C02J6Q493PY/p1646250277182629

For the CLI output for checks status:

why does a warning include the text Only?   Only 1 warning. 0 failure. 0 error. 0 pass. If there are more than one warnings, the Only is still there: Only 2 warnings. 0 failure. 0 errors. 0 pass.  Are 50 warnings still Only? 100?   However,  the failures trump the warnings in order of precedence so 1 failure and 2 warnings seems fine.  Oops! 1 failure. 2 warnings. 0 errors. 0 pass.

Sometimes it says 0 warnings and sometimes it says No warnings— is that intentional? All is good. No failures. No warnings. No errors.   Oops! 1 failure. 0 warnings. 0 errors. 0 pass.

Can we change the output message to apply plural where appropriate? Oops! 1 failures.   0 pass.  2 pass.  0 failure

Why does the word  Oops! appear when there is a failure? It implies that something is wrong when, really, a failed test means that something is working correctly/as expected!  Maybe instead: Note ? The Damn! for an error seems about right, tho. Oops for errors is spot on.

**Comment by janet-can** [comment]
Oh, heh, both of those are mine. I transferred my notes in Slack to a ticket in soda-sql-v3 which has now been transferred here. Good memory, @tombaeyens ! ;)
