### ISSUE TITLE
Agent scan wrapper

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-core#1309]
There needs to be a wrapper for running a scan in the agent.  It's the code / container that needs to run on the pod that is launched for executing 1 scan.

@dirkgroenen @jmarien Can you add all links that contain prior knowledgee / analysis on this task to this issue so we can read up on what is decided?  

What is the expected result?  Python code or a docker file?
In which codebase/repo it should be contributed?

What I understand so far about the goal:
* Docker container starts
* Python code should 
  * Read credentials from AWS secrets manager.  These are the credentials that are configured during the data source onboarding flow by the user in AWS secrets manager
  * Expose the credentials as environment variables
  * Launch a scan programmatically ensuring that the environment variables are resolved.

@m1n0 will already start review today the code from Soda SQL that reads keys from the AWS secrets manager.  So that early next week he can easily add that.

**Comment by jmarien** [comment]
SODA-165

**Comment by dirkgroenen** [comment]
@tombaeyens for as far as we have a Feature Spec for this most information can be found in the following doc on slite: https://sodadata.slite.com/app/docs/pnXsfCU2e0syLm. 

So a short summary of previous discussions from my pov: 
1. @jmarien is taking care of all agent related things. This includes infrastructure, as well as the application which communicates with the Soda Cloud in order to receive jobs and/or schedules. 
2. The "Agent" will spawn a container which includes Soda Core and it's "wrapper". This will be the responsible process for actually executing the scan and pushing the results to Soda Core. 

The wrapper will be invoked by the Soda Agent and it will be provided with:
- process env vars containing secrets (or sth related to the Secrets Manager - please check and align with @jmarien)
- the [Cloud] Scan Definition which needs to be executed 

Using all of this information the "wrapper" will continue to: 
- Make a call to Soda Cloud's [`SodaCoreDefinitionExecutionContextAsyncRequest`](https://github.com/sodadata/soda/blob/master/soda-model/src/main/java/io/sodadata/scans/context/SodaCoreDefinitionExecutionContextAsyncRequest.java) command including the `scanDefinitionName`.  (Note this call being [**async**](https://sodadata.slite.com/app/docs/JeLSPHLXR5_NMJ)) 
- The command will return the following information:
  - `defaultDataSourceName`  -  this is the defaultDataSourceName which needs to be passed along to Soda Core
  - `archiveLocationUrl` - this is a temp link to the location of the archive containing all files. This needs to be downloaded, extracted and passed along to Soda Core
  - `configurationFiles` - this is a list of all configuration files in the `archive` 
  - `checkFiles` - this is a list of check files in the `archive`

This is basically it from the wrapper POV. At this point it will have received all information, prepared the Soda Core scan and triggered it. It's now back to Soda Core to run the scan and upload the results to Soda Cloud. 

---

There are some sequence diagrams in the mentioned Slite document. If any other questions: please let me know! :+1:

**Comment by tombaeyens** [comment]
@dirkgroenen can you elaborate on the async [SodaCoreDefinitionExecutionContextAsyncRequest](https://github.com/sodadata/soda/blob/master/soda-model/src/main/java/io/sodadata/scans/context/SodaCoreDefinitionExecutionContextAsyncRequest.java) ?

Does this correspond in the Slite page, to `coreAgentUpdateInstruction` ?

Wondering if there is a relation between this async `SodaCoreDefinitionExecutionContextAsyncRequest`  command and the commands that Soda Core scan itself will send to Soda Cloud.

**Comment by tombaeyens** [comment]
@jmarien is SODA-165 a jira issue?  If so link would be great.  Tried to search myself but couldn't access jira yet

**Comment by tombaeyens** [comment]
First of all: My main goal is to help facilitate alignment between @jmarien and @dirkgroenen, not to influence the existing planned designs.  So if things that I describe below here are already worked out, then that should be pointed out and be looked at first.

@jmarien wrote:

> I am aligned with Dirk’s comment and feedback. The way the secrets and scan instructions are being passed is the only thing we need to align on and I remember [@Tom](https://sodadata.slack.com/team/UAX5DFA2W) saying weeks ago he wanted to have that in Soda Core or close to Soda Core. So the idea would be that Soda Core (or the wrapper) accepts some parameters which hold the scan instructions (already there, mostly) and accept for example either secrets in the ENV or paths to Secrets Manager and later other secrets vaults so Soda Core could use the AWS SDK (and later other SDK’s) to read those secrets directly.

My assumption is that users will author data source configs in Soda Cloud like this:

```
data_source my_database_name:
  type: postgres
  connection:
    host: db
    username: ${SODA_POSTGRES_USERNAME}
    password: ${SODA_POSTGRES_PASSWORD}
  database: postgres
  schema: public
```

Next the user is instructed to go into the AWS secrets manager and configure those variables.  I m assuming this has to be within a certain secrets manager path, scope or prefix structure or something like that.

Eg user sets `some.secrets.manager.prefix.SODA_POSTGRES_USERNAME` and `some.secrets.manager.prefix.SODA_POSTGRES_PASSWORD`

Then, when a scan pod is launched, the wrapper simply loads all the secrets starting with eg `some.secrets.manager.prefix.SODA_`, removes the prefix `some.secrets.manager.prefix.` and sets those as environment variables.

This way all the `SODA_...` credentials are being set in all the pods.

Is this aligned or conflicting with the planned work?  If there is already things written on this, where can I find it?

**Comment by jmarien** [comment]
We have been discussing this yesterday in the call. We will need to align on how the secrets can be provided through the Helm chart (ideally) to make it easier and simple for the users to get started with. The current implementation already works like that and can use Secrets Manager through EKS's implementation directly (EKS uses Secrets Manager for storing EKS Kubernetes Secrets). 

This way we can easily provide the Soda Core container (or its wrapper) with the Secrets as ENV vars. Additional pointers will follow here and in a planned discussion tomorrow as well.

**Comment by dirkgroenen** [comment]
> @dirkgroenen can you elaborate on the async [SodaCoreDefinitionExecutionContextAsyncRequest](https://github.com/sodadata/soda/blob/master/soda-model/src/main/java/io/sodadata/scans/context/SodaCoreDefinitionExecutionContextAsyncRequest.java) ?
> 
> Does this correspond in the Slite page, to `coreAgentUpdateInstruction` in the sequence diagram at the end of that page? I also tried searching for the request name in the page but didn't find it.
> 
> Wondering if there is a relation between this async `SodaCoreDefinitionExecutionContextAsyncRequest` command and the commands that Soda Core scan itself will send to Soda Cloud.

It's the request which the Core Wrapper needs to use in order to retrieve all SodaCL and configuration files from the Soda Cloud. In the document it's mentioned here: https://sodadata.slite.com/app/docs/pnXsfCU2e0syLm#a36fa1ff. 

I see that the sequence diagram shown in the doc is indeed not representing that part, it's mainly focused on the Agent/Cloud relation. 

So what will happen:
1. Soda Agent will spawn the process with the required parameters 
2. Soda Core Wrapper will make a call to Soda Cloud to fetch the Scan Definition Archive 
3. Soda Cloud will compose this archive and return a link to the download location, as well as paths to all files included in the archive (configuration and check files).
4. Soda Core Wrapper will download the archive, unwrap it and pass along the files to Soda Core

The call is an Async request. This implies it will try to reply with the [SodaCoreDefinitionExecutionContextAsyncResult](https://github.com/sodadata/soda/blob/master/soda-model/src/main/java/io/sodadata/scans/context/SodaCoreDefinitionExecutionContextAsyncResult.java), but if the request takes too long it will return an [AsyncResponse](https://github.com/sodadata/soda/blob/eef6ec6063fddd09894b996279cc00d26de22322/soda-client/src/main/java/io/sodadata/client/AsyncResponse.java).

This response contains an `asyncRequestId` which can then be used to [poll the status of the request](https://github.com/sodadata/soda/blob/eef6ec6063fddd09894b996279cc00d26de22322/soda-client/src/main/java/io/sodadata/client/api/frontend/AsyncRequestQuery.java) and get the original request response. 

---

All of the above is mostly important for the one creating the wrapper. If help is needed from our team in the form of Milan or Antonin please let me know.
