### ISSUE TITLE
For each checks does not recognize schema names for Redshift

### ISSUE THREAD

**Issue by aspexdaniel** [sodadata/soda-core#1573]
```
for each dataset T:
  datasets:
    - vendor.test

  checks:
    - freshness(last_updated_time) < 30d
```
ERROR: Cross data source table sets not yet supported. vendor.test refers to non default data source vendor. Default data source is redshift.

datasource is defined as 'redshift'. Seems Soda doesn't support **schema_name.table_name** in for-each checks?

**Comment by jmarien** [comment]
SODA-1136

**Comment by m1n0** [comment]
hi @aspexdaniel ! Thank for reporting this, I am trying to understand your case here. 

Normally Soda considers a data source to include a schema, i.e. you would normally need to define separate data sources for separate schemas. This is by design to accommodate differences between how different data sources work. Are you using the `schema.table` notation with Redshift in your standard (i.e. not for-each) checks?

**Comment by aspexdaniel** [comment]
@m1n0 
yes I'm using `schema.table` for other checks, and it did work. I have two schemas: vendor and public, other checks just use
` checks for public.*** ` and ` checks for vendor.*** `

**Comment by m1n0** [comment]
@aspexdaniel I see thank you. The thinking behind data sources in Soda is that a data source is equivalent to a "dataset container", i.e. it includes the setting of what is usually the schema. The fact that you can use `schema.table` with Redshift is not entirely on purpose, it works because Redshift and the psycopg connector are not strict about specifying a schema. 

In order to make Soda compatible with different types of data source we will not change the behaviour for for-each checks here, there are other features that require the schema to be already set implicitly and there are more to come. What I would suggest is simply define data sources per schema and run the checks that way.
