### ISSUE TITLE
Since 3.0.13, duplicate_count not evaluating with dataset filter

### ISSUE THREAD

**Issue by janet-can** [sodadata/soda-core#1695]
Two reports have been made regarding a similar issue using Soda Core 3.0.13: for checks that use a dataset filter, the duplicate_count metric is no longer being evaluated. 

Example of checks YAML:
```
filter master [lastday]:
  name: Records yesterday
  where: SUMMARY_DATE = current_date - 1

checks for master [lastday]:
  - row_count > 0:
      name: Last partition freshness
  - duplicate_count(DATA:account_id) = 0
```

Scan output:
```
...
SELECT DATA:id, DATA:workspace_id, DATA:email, frequency
FROM frequencies
WHERE frequency > 1 | 000904 (42000): SQL compilation error: error line 9 at position 19
invalid identifier 'DATA'
ERROR  | Metrics 'duplicate_count' were not computed for check 'duplicate_count(DATA:id, DATA:workspace_id, DATA:email) = 0'
```

Refer to threads: 
- https://soda-community.slack.com/archives/C038FFU79J5/p1668788327024629  
- https://soda-community.slack.com/archives/C038FFU79J5/p1668541963700869

**Comment by jmarien** [comment]
SODA-1314

**Comment by m1n0** [comment]
Dataset filters were just a bystander here, this was due to exclude_columns functionality combined with complex types generating invalid queries. Partial fix has been released - if no exclude_columns is used then complex types work again in duplicate checks. If exclude_columns is used with standard types that works as well, but if exclude_columns is used in combination with complex types, then duplicate check will not work for now. 

This limitation will be fixed when we start supporting complex types.
