### ISSUE TITLE
Oracle connection fails

### ISSUE THREAD

**Issue by dinakarmu** [sodadata/soda-core#2036]
The oracle connection fails with the error saying, no configuration directory defined for tnsnames. No matter what, I am unable to provide the default path of tnsnames.ora in network/admin. Is there a parameter that could be passed to provide the path for tnsnames.ora. Tried a lot, just couldn’t figure out. This is in windows OS. The document clearly says that Soda supports Oracle version 21.3 or greater, has anyone tried on 19c.

**Comment by tools-soda** [comment]
SAS-3072

**Comment by m1n0** [comment]
Soda currently supports Thin connection mode where this might be an issue. User on our Slack community had success by installing Oracle client locally and enabling Thick mode and then invoking Soda programmatically in the same session.

>  Dinakar Ullas
After trying without giving up and reading through the documentations, I made it work on 19c in a windows machine. soda-core-oracle uses oracledb module and oracledb can either connect using thin client or thick client. it turns out that thin client requires wallets to be setup and things like these can take a lot of time especially in huge enterprises due to audit, security and compliance procedures. Thick client needs downloading oracle instant client 64 bit libraries, do not download the latest one(there seems to be a defect), but the one version below the latest works. In the soda core python script, enable thick client mode and pass the two parameters like this below:
oracledb.init_oracle_client(lib_dir=path to the instant client folder, config_dir=path to the TNS file)
This should do the trick.

Closing this issue as we are not currently planning to support Thick client mode natively in Soda.

- [Python-oracledb docs](https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html)
- [Slack thread](https://soda-community.slack.com/archives/C038FFU79J5/p1710630510737599)
