### ISSUE TITLE
Issue to install soda-core-pandas-dask via Poetry in Windows

### ISSUE THREAD

**Issue by doug-pires** [sodadata/soda-core#2085]
I tried to install the soda-core-pandas-dask using Poetry via PowerShell ( windows OS )

After running `poetry add soda-core-pandas-dask` throw an error for the package **dask-sql**.

![image](https://github.com/sodadata/soda-core/assets/62630272/9c3b0fc3-8b3a-4b9c-a5dc-d92e31f6a718)

The message I got:
![image](https://github.com/sodadata/soda-core/assets/62630272/b7db3058-6185-4c73-b9d1-e579cbb87596)

PS. I installed it with no issues in Ubuntu ( WSL ) 
![image](https://github.com/sodadata/soda-core/assets/62630272/fa996462-5101-47e0-8aa5-0fd68410879e)

**Comment by tools-soda** [comment]
SAS-3480

**Comment by m1n0** [comment]
Hi, this is not related to Soda in any way, you are having issues because dask-sql does not provide prebuilt binaries for you version of Python, which I assume is 3.11. See dask-sql issue [here](https://github.com/dask-contrib/dask-sql/issues/1306).

You can either use a version of Python for which dask-sql provides a prebuilt binary or install the necessary system requirements to build it yourself. As your log says, you need a Rust complier for that.
